### PR TITLE
`rix()`: add {rix} version string to call metainfo

### PR DESCRIPTION
**Pull request by philipp-baumann**
also update `inst/extdata/default.nix` generated with `rix::rix()` from this PR branch.

### CODE REVIEW

**Review by b-rodrigues — APPROVED** [review]
can you add the shell hook to inst/extdada/default.nix back ?

**Comment by philipp-baumann** [comment]
@b-rodrigues one moment, I also need to add the shellHook

**Comment by philipp-baumann** [comment]
sorry just this second realized in parallel. ;-)

**Comment by philipp-baumann** [comment]
> @b-rodrigues one moment, I also need to add the shellHook

something is not in order with the formatting (spaces etc.) when I use `rix::rix()` of current master if I compare to current `inst/extdata/default.nix`. Did you manually format?

**Comment by b-rodrigues** [comment]
yes 😂 I'm planning to rewrite rix because it's too janky as it is

**Comment by philipp-baumann** [comment]
> yes joy I'm planning to rewrite rix because it's too janky as it is

did it manually, please quickly check, but it should be ok.

**Comment by philipp-baumann** [comment]
`shell_hook` parsing to nix `shellHook` highly wanted I'd say :-)

**Pull request merged**
