### PR TITLE
fix locale

### PR DESCRIPTION
**Pull request by philipp-baumann**
finalizes #50 in `rix::rix()`

### CODE REVIEW

**Comment by philipp-baumann** [comment]
- now, `tex_pkgs = NULL` is correctly propagated.

**Comment by philipp-baumann** [comment]
@b-rodrigues I added the possibility of `options(rix.nix_locale_variables = list()` settings and the allowed locale variables to the help. Also a short recommendation to use `"en_US.UTF-8"`.

**Comment by philipp-baumann** [comment]
- guess we can add a remark about locale and reproducibility plus glibc size on linux somewhere in the README, and possibly vignettes, too.

**Comment by philipp-baumann** [comment]
- once this PR is merged, I will update the commit identifier of {rix} in `create_default_nix()` and the resulting `inst/extdata/default.nix`. Once this is all done, I will bump and update news.

**Review by b-rodrigues — APPROVED** [review]
very nice, many thanks! The only thing that still amazes me is why installing glibcLocalesUtf8 works on Darwin. But other than that, this is great!

**Pull request merged**
