### PR TITLE
Adressing the r-opensci review

### PR DESCRIPTION
**Pull request by b-rodrigues**
Let's push our commits to this branch

### CODE REVIEW

**Comment by b-rodrigues** [comment]
Still several things to deal with:

- https://github.com/b-rodrigues/rix/issues/152
- https://github.com/b-rodrigues/rix/issues/151

Several comments need answer not in code.

**Comment by philipp-baumann** [comment]
@b-rodrigues why is fusen putting arrow in imports? we have no code to state do do so, i'm confused.

**Comment by philipp-baumann** [comment]
also, we don't want dplyr.

**Comment by b-rodrigues** [comment]
> @b-rodrigues why is fusen putting arrow in imports? we have no code that states to do so, i'm confused.

i’m not sure I follow what you mean, I’ve never seen arrow being added to the DESCRIPTION

**Comment by philipp-baumann** [comment]
> > @b-rodrigues why is fusen putting arrow in imports? we have no code that states to do so, i'm confused.
> 
> i’m not sure I follow what you mean, I’ve never seen arrow being added to the DESCRIPTION

```{r}
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin22.6.0 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /nix/store/csam52q8ksy40sa4q7z5ijx7jixivrby-blas-3/lib/libblas.dylib 
LAPACK: /nix/store/i2ddi7h4bn0qr1bms5bilccp0rd9fnm5-openblas-0.3.26/lib/libopenblasp-r0.3.26.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] generics_0.1.3    tidyr_1.3.1       utf8_1.2.4        xml2_1.3.6       
 [5] stringi_1.8.3     attachment_0.4.1  hms_1.1.3         digest_0.6.35    
 [9] magrittr_2.0.3    pkgload_1.3.4     fastmap_1.1.1     jsonlite_1.8.8   
[13] rprojroot_2.0.4   pkgbuild_1.4.4    sessioninfo_1.2.2 brio_1.1.4       
[17] backports_1.4.1   urlchecker_1.0.1  promises_1.3.0    httr_1.4.7       
[21] purrr_1.0.2       fansi_1.0.6       codetools_0.2-20  cli_3.6.2        
[25] shiny_1.8.1.1     rlang_1.1.3       crayon_1.5.2      ellipsis_0.3.2   
[29] fusen_0.5.2       withr_3.0.0       remotes_2.5.0     cachem_1.0.8     
[33] yaml_2.3.8        devtools_2.4.5    tools_4.3.3       parsermd_0.1.3   
[37] tzdb_0.4.0        memoise_2.0.1     checkmate_2.3.1   dplyr_1.1.4      
[41] httpuv_1.6.15     curl_5.2.1        vctrs_0.6.5       R6_2.5.1         
[45] mime_0.12         lifecycle_1.0.4   stringr_1.5.1     fs_1.6.3         
[49] htmlwidgets_1.6.4 usethis_2.2.3     miniUI_0.1.1.1    pkgconfig_2.0.3  
[53] desc_1.4.3        pillar_1.9.0      later_1.3.2       rix_0.6.0        
[57] glue_1.7.0        profvis_0.3.8     Rcpp_1.0.12       tidyselect_1.2.1 
[61] xfun_0.43         tibble_3.2.1      sys_3.4.2         rstudioapi_0.16.0
[65] knitr_1.46        xtable_1.8-4      htmltools_0.5.8.1 testthat_3.2.1   
[69] readr_2.1.5       compiler_4.3.3    roxygen2_7.3.1   
> fusen::inflate_all_no_check()
✔ The flat file flat_available_R.Rmd is going to be inflated
✔ The flat file flat_cicd.Rmd is going to be inflated
✔ The flat file flat_cran_archive.Rmd is going to be inflated
✔ The flat file flat_data_doc.Rmd is going to be inflated
✔ The flat file flat_fetchers.Rmd is going to be inflated
✔ The flat file flat_find_rev.Rmd is going to be inflated
✔ The flat file flat_get_latest.Rmd is going to be inflated
✔ The flat file flat_get_os.Rmd is going to be inflated
✔ The flat file flat_get_sri_hash_deps.Rmd is going to be inflated
✔ The flat file flat_nix_build.Rmd is going to be inflated
✔ The flat file flat_rix_init.Rmd is going to be inflated
✔ The flat file flat_rix.Rmd is going to be inflated
✔ The flat file flat_with_nix.Rmd is going to be inflated
✔ The flat file flat_zzz.Rmd is going to be inflated
✔ The flat file a-getting_started.Rmd is going to be inflated
── config file for dev/b1-linux_win.Rmd ─────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/b2-macos.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/c-building_envs_with_rix.Rmd ─────────────────────────────────────────────────────────────────────────────
── config file for dev/d1-install_r_pkgs.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/d2-install_sys_pkgs.Rmd ──────────────────────────────────────────────────────────────────────────────────
── config file for dev/e-interactive_use.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_available_R.Rmd ─────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_cicd.Rmd ────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_cran_archive.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_data_doc.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_fetchers.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_find_rev.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_latest.Rmd ──────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_os.Rmd ──────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_sri_hash_deps.Rmd ───────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_nix_build.Rmd ───────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_rix.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_rix_init.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_with_nix.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_zzz.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-inst_rix.Rmd ───────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-literate_programming.Rmd ───────────────────────────────────────────────────────────────────────────────
── config file for dev/z-pkgs_with_remotes.Rmd ──────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-raps_with_nix.Rmd ──────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-save_r_nix_revs.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-subshells.Rmd ──────────────────────────────────────────────────────────────────────────────────────────
── check not registered files ───────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Some files in your package are not registered in the configuration file: dev/config_fusen.yaml
fusen uses a configuration file to store the structure of your package and help you clean it when needed.
You will find a list of unregistered files there: csv_file that you can open with `file.edit('dev/config_not_registered.csv')`
Delete unregistered files that you do not need anymore. Then run `fusen::register_all_to_config()`.
After that, this message should not appear in your next `fusen::inflate_all()` calls.
For more information, read `vignette('register-files-in-config (`vignette(fusen::register-files-in-config)`)', package = 'fusen')`
cli-62920-470
Documentation parameters were restored from attachment config file.
Updating rix documentation
Writing NAMESPACE
ℹ Loading rix
ℹ The package "arrow" is required.
✖ Would you like to install it?

1: Yes
2: No
```

**Comment by philipp-baumann** [comment]
@b-rodrigues I am using exactly the same version of {fusen}. Because of some hidden wizardry, it produces different DESCRIPTION. 

```r
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin22.6.0 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /nix/store/csam52q8ksy40sa4q7z5ijx7jixivrby-blas-3/lib/libblas.dylib 
LAPACK: /nix/store/i2ddi7h4bn0qr1bms5bilccp0rd9fnm5-openblas-0.3.26/lib/libopenblasp-r0.3.26.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] generics_0.1.3    tidyr_1.3.1       utf8_1.2.4        xml2_1.3.6       
 [5] stringi_1.8.3     attachment_0.4.1  hms_1.1.3         digest_0.6.35    
 [9] magrittr_2.0.3    pkgload_1.3.4     fastmap_1.1.1     jsonlite_1.8.8   
[13] rprojroot_2.0.4   pkgbuild_1.4.4    sessioninfo_1.2.2 brio_1.1.4       
[17] backports_1.4.1   urlchecker_1.0.1  promises_1.3.0    httr_1.4.7       
[21] purrr_1.0.2       fansi_1.0.6       codetools_0.2-20  cli_3.6.2        
[25] shiny_1.8.1.1     rlang_1.1.3       crayon_1.5.2      ellipsis_0.3.2   
[29] fusen_0.5.2       withr_3.0.0       remotes_2.5.0     cachem_1.0.8     
[33] yaml_2.3.8        devtools_2.4.5    tools_4.3.3       parsermd_0.1.3   
[37] tzdb_0.4.0        memoise_2.0.1     checkmate_2.3.1   dplyr_1.1.4      
[41] httpuv_1.6.15     curl_5.2.1        vctrs_0.6.5       R6_2.5.1         
[45] mime_0.12         lifecycle_1.0.4   stringr_1.5.1     fs_1.6.3         
[49] htmlwidgets_1.6.4 usethis_2.2.3     miniUI_0.1.1.1    pkgconfig_2.0.3  
[53] desc_1.4.3        pillar_1.9.0      later_1.3.2       rix_0.6.0        
[57] glue_1.7.0        profvis_0.3.8     Rcpp_1.0.12       tidyselect_1.2.1 
[61] xfun_0.43         tibble_3.2.1      sys_3.4.2         rstudioapi_0.16.0
[65] knitr_1.46        xtable_1.8-4      htmltools_0.5.8.1 testthat_3.2.1   
[69] readr_2.1.5       compiler_4.3.3    roxygen2_7.3.1   
> fusen::inflate_all_no_check()
✔ The flat file flat_available_R.Rmd is going to be inflated
✔ The flat file flat_cicd.Rmd is going to be inflated
✔ The flat file flat_cran_archive.Rmd is going to be inflated
✔ The flat file flat_data_doc.Rmd is going to be inflated
✔ The flat file flat_fetchers.Rmd is going to be inflated
✔ The flat file flat_find_rev.Rmd is going to be inflated
✔ The flat file flat_get_latest.Rmd is going to be inflated
✔ The flat file flat_get_os.Rmd is going to be inflated
✔ The flat file flat_get_sri_hash_deps.Rmd is going to be inflated
✔ The flat file flat_nix_build.Rmd is going to be inflated
✔ The flat file flat_rix_init.Rmd is going to be inflated
✔ The flat file flat_rix.Rmd is going to be inflated
✔ The flat file flat_with_nix.Rmd is going to be inflated
✔ The flat file flat_zzz.Rmd is going to be inflated
✔ The flat file a-getting_started.Rmd is going to be inflated
── config file for dev/b1-linux_win.Rmd ─────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/b2-macos.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/c-building_envs_with_rix.Rmd ─────────────────────────────────────────────────────────────────────────────
── config file for dev/d1-install_r_pkgs.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/d2-install_sys_pkgs.Rmd ──────────────────────────────────────────────────────────────────────────────────
── config file for dev/e-interactive_use.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_available_R.Rmd ─────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_cicd.Rmd ────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_cran_archive.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_data_doc.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_fetchers.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_find_rev.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_latest.Rmd ──────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_os.Rmd ──────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_get_sri_hash_deps.Rmd ───────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_nix_build.Rmd ───────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_rix.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_rix_init.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_with_nix.Rmd ────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/flat_zzz.Rmd ─────────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-inst_rix.Rmd ───────────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-literate_programming.Rmd ───────────────────────────────────────────────────────────────────────────────
── config file for dev/z-pkgs_with_remotes.Rmd ──────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-raps_with_nix.Rmd ──────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-save_r_nix_revs.Rmd ────────────────────────────────────────────────────────────────────────────────────
── config file for dev/z-subshells.Rmd ──────────────────────────────────────────────────────────────────────────────────────────
── check not registered files ───────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Some files in your package are not registered in the configuration file: dev/config_fusen.yaml
fusen uses a configuration file to store the structure of your package and help you clean it when needed.
You will find a list of unregistered files there: csv_file that you can open with `file.edit('dev/config_not_registered.csv')`
Delete unregistered files that you do not need anymore. Then run `fusen::register_all_to_config()`.
After that, this message should not appear in your next `fusen::inflate_all()` calls.
For more information, read `vignette('register-files-in-config (`vignette(fusen::register-files-in-config)`)', package = 'fusen')`
cli-62920-470
Documentation parameters were restored from attachment config file.
Updating rix documentation
Writing NAMESPACE
ℹ Loading rix
ℹ The package "arrow" is required.
✖ Would you like to install it?

1: Yes
2: No
```

**Comment by b-rodrigues** [comment]
Are you inflating from this branch? Just inflated again, it's actually even automatically removing arrow and dplyr for me:

```
✔ There are no unregistered files.
Documentation parameters were restored from attachment config file.
Updating rix documentation
Writing NAMESPACE
ℹ Loading rix
Writing NAMESPACE
ℹ Loading rix
[-] 2 package(s) removed: arrow, dplyr.
── Launching check() ────────────────────
```

But no matter, one issue at a time. Let's try to see what's going on once we merge this to master.

**Comment by b-rodrigues** [comment]
Also, you have a lot more packages loaded for some reason:

```
> devtools::load_all()
ℹ Loading rix
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: openSUSE Tumbleweed

Matrix products: default
BLAS/LAPACK: /nix/store/0wbgymcg4aj6n9dpsl5645j3zj1rcl64-blas-3/lib/libblas.so.3;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Luxembourg
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rix_0.6.0      testthat_3.2.1

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.8    miniUI_0.1.1.1    compiler_4.3.3    brio_1.1.4       
 [5] promises_1.3.0    Rcpp_1.0.12       stringr_1.5.1     later_1.3.2      
 [9] fastmap_1.1.1     mime_0.12         R6_2.5.1          curl_5.2.1       
[13] htmlwidgets_1.6.4 desc_1.4.3        profvis_0.3.8     rprojroot_2.0.4  
[17] shiny_1.8.1.1     rlang_1.1.3       cachem_1.0.8      stringi_1.8.3    
[21] httpuv_1.6.15     sys_3.4.2         fs_1.6.3          pkgload_1.3.4    
[25] memoise_2.0.1     cli_3.6.2         withr_3.0.0       magrittr_2.0.3   
[29] digest_0.6.35     rstudioapi_0.16.0 xtable_1.8-4      remotes_2.5.0    
[33] devtools_2.4.5    lifecycle_1.0.4   vctrs_0.6.5       glue_1.7.0       
[37] urlchecker_1.0.1  codetools_0.2-20  sessioninfo_1.2.2 pkgbuild_1.4.4   
[41] httr_1.4.7        purrr_1.0.2       tools_4.3.3       usethis_2.2.3    
[45] ellipsis_0.3.2    htmltools_0.5.8.1

```

**Comment by b-rodrigues** [comment]
Merging this to avoid future conflicts, and then continue on another PR

**Pull request merged**
