### PR TITLE
Patch: oror in if

### PR DESCRIPTION
**Pull request by philipp-baumann**
Hi @b-rodrigues thanks for making this great package! :-) This is just a very minor patch PR. Cheers, Philipp

### CODE REVIEW

**Comment by b-rodrigues** [comment]
many thanks! Unfortunately I'll have to reject your PR, because I use the {fusen} package to develop this one, so changes have to be made in the `.Rmd` files that generate the .R files. I've added this here: https://github.com/b-rodrigues/rix/commit/576c350255687d90c446588ddfcc6760426401a1

If you do further testing, please let me know how it goes :smile:

**Comment by b-rodrigues** [comment]
just to give more details: the change was made on this line in the Rmd file: https://github.com/b-rodrigues/rix/blob/576c350255687d90c446588ddfcc6760426401a1/dev/build_envs.Rmd#L421

**Comment by philipp-baumann** [comment]
> many thanks! Unfortunately I'll have to reject your PR, because I use the {fusen} package to develop this one, so changes have to be made in the `.Rmd` files that generate the .R files. I've added this here: [576c350](https://github.com/b-rodrigues/rix/commit/576c350255687d90c446588ddfcc6760426401a1)
> 
> If you do further testing, please let me know how it goes 😄

aah, i oversaw that ;-) no worries.

**Comment by philipp-baumann** [comment]
happy to test further and give feedback if I have questions/suggestions :100:

**Pull request closed without merging**
