### PR TITLE
Compute hash of git and CRAN archive packages locally if nix is installed

### PR DESCRIPTION
**Pull request by b-rodrigues**
WIP

Kinda works, but snapshot tests for rix/ don't pass anymore, and weirdly enough it seems unrelated

### CODE REVIEW

**Comment by philipp-baumann** [comment]
```r
> devtools::load_all(".")
ℹ Loading rix
> url <- paste0("https://github.com/rap4all/housing/", "archive/",
+   "1c860959310b80e67c41f7bbdc3e84cef00df18e", ".tar.gz")
> 
> hash_url(url = url)
$sri_hash
[1] "sha256-s4KGtfKQ7hL0sfDhGb4BpBpspfefBN6hf+XlslqyEn4="

$deps
[1] "dplyr ggplot2 janitor purrr readxl rlang rvest stringr tidyr"
```

**Comment by philipp-baumann** [comment]
- [ ] Remove git2r
- [ ] add an option via `options()` to demand local or remote hashing of url resources. 
- [ ] Redesign the interface

**Comment by b-rodrigues** [comment]
The default behavior should be to hash locally if nix-hash is present,  otherwise use the online service and add message to inform the user, what do you think ?

**Comment by philipp-baumann** [comment]
https://github.com/NixOS/nix/pull/7690

**Pull request merged**
