### PR TITLE
add default nix config to ship with pkg

### PR DESCRIPTION
**Pull request by philipp-baumann**
addresses #14

### CODE REVIEW

**Comment by philipp-baumann** [comment]
@b-rodrigues guess on Win there is a build failure because of time consumed in the CI/CD pipeline.

**Comment by philipp-baumann** [comment]
Guess it makes sense to include RStudio as IDE in default config?

**Comment by philipp-baumann** [comment]
Also, we currently have a fixed commit tag for {rix}. Maybe in future it would make sense to refer to latest stable pkg commit, if you decide to publish it there :-)

**Comment by b-rodrigues** [comment]
I made some changes to your pull request before merging:

- the environment in inst/extdata/default.nix does not install RStudio anymore. This is because this will be used for a temporary Nix shell simply to create a first, complete environment
- changed some stuff to the readme

Let me know what you think about the readme :)

**Comment by philipp-baumann** [comment]
like it!

**Comment by philipp-baumann** [comment]
Will get back to tmrw about readme. Need to catch some sleep 😎

**Pull request merged**
